// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhk-bPj1Va_Tfj5N8-InCbEKre9auD5ec',
    appId: '1:160770725455:web:08f2f35d6c38b754febc3a',
    messagingSenderId: '160770725455',
    projectId: 'heathhub-bca8d',
    authDomain: 'heathhub-bca8d.firebaseapp.com',
    databaseURL: 'https://heathhub-bca8d-default-rtdb.firebaseio.com',
    storageBucket: 'heathhub-bca8d.appspot.com',
    measurementId: 'G-SG2C42QZS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq6_vBWxIRD9D184GVXLLB0V07xOFJWLA',
    appId: '1:160770725455:android:2dab2ecdec0b0ce9febc3a',
    messagingSenderId: '160770725455',
    projectId: 'heathhub-bca8d',
    databaseURL: 'https://heathhub-bca8d-default-rtdb.firebaseio.com',
    storageBucket: 'heathhub-bca8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnNUFu-wky0Td6ymMOAfh8kNrXNDRQRRE',
    appId: '1:160770725455:ios:7fc423ee42cc5c1dfebc3a',
    messagingSenderId: '160770725455',
    projectId: 'heathhub-bca8d',
    databaseURL: 'https://heathhub-bca8d-default-rtdb.firebaseio.com',
    storageBucket: 'heathhub-bca8d.appspot.com',
    iosBundleId: 'com.example.healthHubProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnNUFu-wky0Td6ymMOAfh8kNrXNDRQRRE',
    appId: '1:160770725455:ios:7fc423ee42cc5c1dfebc3a',
    messagingSenderId: '160770725455',
    projectId: 'heathhub-bca8d',
    databaseURL: 'https://heathhub-bca8d-default-rtdb.firebaseio.com',
    storageBucket: 'heathhub-bca8d.appspot.com',
    iosBundleId: 'com.example.healthHubProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhk-bPj1Va_Tfj5N8-InCbEKre9auD5ec',
    appId: '1:160770725455:web:c6aa513d0cb7d874febc3a',
    messagingSenderId: '160770725455',
    projectId: 'heathhub-bca8d',
    authDomain: 'heathhub-bca8d.firebaseapp.com',
    databaseURL: 'https://heathhub-bca8d-default-rtdb.firebaseio.com',
    storageBucket: 'heathhub-bca8d.appspot.com',
    measurementId: 'G-M6QYW7BD34',
  );
}
